# Generated by Django 6.0.3 on 2026-03-11 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
        ('intake', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyintake',
            name='food',
        ),
        migrations.AddField(
            model_name='dailyintake',
            name='custom_food',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='foods.customfood'),
        ),
        migrations.AddField(
            model_name='dailyintake',
            name='public_food',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='foods.foodcatalogue'),
        ),
    ]
